# Generated by Django 3.0.8 on 2020-08-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200821_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
